import 'package:visit_1000_hills/models/Apartment.dart';

class ApartmentService {
  // Simulate fetching apartment data
  static List<Apartment> getApartments() {
    return [
      Apartment(
        name: 'Luxury Studio Apartment',
        description: 'A beautiful studio apartment with a modern design.',
        price: 800,
        location: 'Downtown',
        apartmentType: 'Studio',
        imageUrl: 'assets/images/hotels/apart.jpg',
        imageUrls: ['assets/images/hotels/apart.jpg', 'assets/images/hotels/apart.jpg'], // List of image URLs
        floor: 3,
        numberOfRooms: 1,
        area: 500,
        hasParking: true,
        hasSecurityCamera: true,
      ),
      Apartment(
        name: '2 Bedroom Family Apartment',
        description: 'Perfect for small families, with a spacious living room.',
        price: 1200,
        location: 'Suburbs',
        apartmentType: '2 Bedroom',
        imageUrl: 'assets/images/hotels/apart.jpg',
        imageUrls: ['assets/images/hotels/apart.jpg', 'assets/images/hotels/apart.jpg'], // List of image URLs
        floor: 1,
        numberOfRooms: 2,
        area: 850,
        hasParking: true,
        hasSecurityCamera: false,
      ),
  Apartment(
    name: 'Luxury Studio Apartment',
    description: 'A beautiful studio apartment with a modern design.',
    price: 800,
    location: 'Downtown',
    apartmentType: 'Studio',
    imageUrl: 'assets/images/hotels/apart.jpg',
    imageUrls: ['assets/images/hotels/apart.jpg', 'assets/images/hotels/apart.jpg'],
    floor: 3,
    numberOfRooms: 1,
    area: 500,
    hasParking: true,
    hasSecurityCamera: true,
  ),
  Apartment(
    name: '2 Bedroom Family Apartment',
    description: 'Perfect for small families, with a spacious living room.',
    price: 1200,
    location: 'Suburbs',
    apartmentType: '2 Bedroom',
    imageUrl: 'assets/images/hotels/apart.jpg',
    imageUrls: ['assets/images/hotels/apart.jpg', 'assets/images/hotels/apart.jpg'],
    floor: 1,
    numberOfRooms: 2,
    area: 850,
    hasParking: true,
    hasSecurityCamera: false,
  ),
  Apartment(
    name: 'Penthouse Suite',
    description: 'A luxurious penthouse with stunning city views.',
    price: 3000,
    location: 'City Center',
    apartmentType: 'Penthouse',
    imageUrl: 'assets/images/hotels/apart.jpg',
    imageUrls: ['assets/images/hotels/apart.jpg', 'assets/images/hotels/apart.jpg'],
    floor: 10,
    numberOfRooms: 4,
    area: 2000,
    hasParking: true,
    hasSecurityCamera: true,
  ),
  Apartment(
    name: 'Cozy 1 Bedroom Apartment',
    description: 'A small, cozy apartment perfect for singles or couples.',
    price: 650,
    location: 'City Center',
    apartmentType: '1 Bedroom',
    imageUrl: 'assets/images/hotels/apart.jpg',
    imageUrls: ['assets/images/hotels/apart.jpg', 'assets/images/hotels/apart.jpg'],
    floor: 2,
    numberOfRooms: 1,
    area: 450,
    hasParking: false,
    hasSecurityCamera: false,
  ),
  Apartment(
    name: '3 Bedroom Family Apartment',
    description: 'Ideal for families looking for more space.',
    price: 1500,
    location: 'Suburbs',
    apartmentType: '3 Bedroom',
    imageUrl: 'assets/images/hotels/apart.jpg',
    imageUrls: ['assets/images/hotels/apart.jpg', 'assets/images/hotels/apart.jpg'],
    floor: 1,
    numberOfRooms: 3,
    area: 1200,
    hasParking: true,
    hasSecurityCamera: true,
  ),
  Apartment(
    name: 'Modern Loft Apartment',
    description: 'A stylish loft with open spaces and contemporary design.',
    price: 1400,
    location: 'Downtown',
    apartmentType: 'Loft',
    imageUrl: 'assets/images/hotels/apart.jpg',
    imageUrls: ['assets/images/hotels/apart.jpg', 'assets/images/hotels/apart.jpg'],
    floor: 5,
    numberOfRooms: 2,
    area: 1000,
    hasParking: true,
    hasSecurityCamera: true,
  ),
  Apartment(
    name: 'Spacious 4 Bedroom Apartment',
    description: 'Large apartment ideal for bigger families or groups.',
    price: 2000,
    location: 'Suburbs',
    apartmentType: '4 Bedroom',
    imageUrl: 'assets/images/hotels/apart.jpg',
    imageUrls: ['assets/images/hotels/apart.jpg', 'assets/images/hotels/apart.jpg'],
    floor: 2,
    numberOfRooms: 4,
    area: 1600,
    hasParking: true,
    hasSecurityCamera: true,
  ),
  Apartment(
    name: 'Luxury 2 Bedroom Apartment',
    description: 'A modern apartment with high-end finishes and amenities.',
    price: 1800,
    location: 'City Center',
    apartmentType: '2 Bedroom',
    imageUrl: 'assets/images/hotels/apart.jpg',
    imageUrls: ['assets/images/hotels/apart.jpg', 'assets/images/hotels/apart.jpg'],
    floor: 6,
    numberOfRooms: 2,
    area: 1100,
    hasParking: true,
    hasSecurityCamera: true,
  ),
  Apartment(
    name: 'Cozy Studio Apartment',
    description: 'Compact studio apartment with everything you need.',
    price: 750,
    location: 'Suburbs',
    apartmentType: 'Studio',
    imageUrl: 'assets/images/hotels/apart.jpg',
    imageUrls: ['assets/images/hotels/apart.jpg', 'assets/images/hotels/apart.jpg'],
    floor: 2,
    numberOfRooms: 1,
    area: 400,
    hasParking: false,
    hasSecurityCamera: false,
  ),
  Apartment(
    name: 'Beachfront 2 Bedroom Apartment',
    description: 'A relaxing 2-bedroom apartment right by the beach.',
    price: 2200,
    location: 'Beachfront',
    apartmentType: '2 Bedroom',
    imageUrl: 'assets/images/hotels/apart.jpg',
    imageUrls: ['assets/images/hotels/apart.jpg', 'assets/images/hotels/apart.jpg'],
    floor: 1,
    numberOfRooms: 2,
    area: 950,
    hasParking: true,
    hasSecurityCamera: true,
  ),
  Apartment(
    name: 'Studio with Balcony',
    description: 'Charming studio apartment with a private balcony.',
    price: 900,
    location: 'Downtown',
    apartmentType: 'Studio',
    imageUrl: 'assets/images/hotels/apart.jpg',
    imageUrls: ['assets/images/hotels/apart.jpg', 'assets/images/hotels/apart.jpg'],
    floor: 4,
    numberOfRooms: 1,
    area: 550,
    hasParking: true,
    hasSecurityCamera: true,
  ),
      // Add more apartments here
    ];
  }
}
